path:
  #ckpt_path: "./output/ckpt/rkmt16k_LJ"
  #log_path: "./output/log/rkmt16k_LJ"
  #result_path: "./output/result/rkmt16k_LJ"

  #ckpt_path: "./output/ckpt/LJ_soft_hubert_2022_0706"
  #log_path: "./output/log/LJ_soft_hubert_2022_0706"
  #result_path: "./output/result/LJ_soft_hubert_2022_0706"

  #ckpt_path: "./output/ckpt/LJ_hubert_layer7"
  #log_path: "./output/log/LJ_hubert_layer7"
  #result_path: "./output/result/LJ_hubert_layer7"

  #ckpt_path: "./output/ckpt/LJ_hubert_unit_2022_0710"
  #log_path: "./output/log/LJ_hubert_unit_2022_0710"
  #result_path: "./output/result/LJ_hubert_unit_2022_0710"

  ckpt_path: "./output/ckpt/LJ_hubert_layer12"
  log_path: "./output/log/LJ_hubert_layer12"
  result_path: "./output/result/LJ_hubert_layer12"

optimizer:
  batch_size: 32 # 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 100000
